#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vy.Crm.Shared.Proxy
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vy_QualifyLeadAdvanced")]
	public partial class VY_QualifyLeadAdvancedRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "vy_QualifyLeadAdvanced";
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public VY_QualifyLeadAdvancedRequest()
		{
			this.RequestName = "vy_QualifyLeadAdvanced";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vy_QualifyLeadAdvanced")]
	public partial class VY_QualifyLeadAdvancedResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string VY_AccountId = "VY_AccountId";
			public const string VY_ContactId = "VY_ContactId";
			public const string VY_OpportunityId = "VY_OpportunityId";
			public const string VY_Success = "VY_Success";
		}
		
		public const string ActionLogicalName = "vy_QualifyLeadAdvanced";
		
		public VY_QualifyLeadAdvancedResponse()
		{
		}
		
		public System.Guid VY_AccountId
		{
			get
			{
				if (this.Results.Contains("vy_AccountId"))
				{
					return ((System.Guid)(this.Results["vy_AccountId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["vy_AccountId"] = value;
			}
		}
		
		public System.Guid VY_ContactId
		{
			get
			{
				if (this.Results.Contains("vy_ContactId"))
				{
					return ((System.Guid)(this.Results["vy_ContactId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["vy_ContactId"] = value;
			}
		}
		
		public System.Guid VY_OpportunityId
		{
			get
			{
				if (this.Results.Contains("vy_OpportunityId"))
				{
					return ((System.Guid)(this.Results["vy_OpportunityId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["vy_OpportunityId"] = value;
			}
		}
		
		public bool VY_Success
		{
			get
			{
				if (this.Results.Contains("vy_Success"))
				{
					return ((bool)(this.Results["vy_Success"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["vy_Success"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
