#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vy.Crm.Shared.Proxy
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vy_RecalculateForecast")]
	public partial class VY_RecalculateForecastRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string VY_OwnerId = "VY_OwnerId";
		}
		
		public const string ActionLogicalName = "vy_RecalculateForecast";
		
		public Microsoft.Xrm.Sdk.EntityReference VY_OwnerId
		{
			get
			{
				if (this.Parameters.Contains("vy_OwnerId"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["vy_OwnerId"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["vy_OwnerId"] = value;
			}
		}
		
		public VY_RecalculateForecastRequest()
		{
			this.RequestName = "vy_RecalculateForecast";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vy_RecalculateForecast")]
	public partial class VY_RecalculateForecastResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string VY_Forecast = "VY_Forecast";
			public const string VY_OpportunityCount = "VY_OpportunityCount";
		}
		
		public const string ActionLogicalName = "vy_RecalculateForecast";
		
		public VY_RecalculateForecastResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Money VY_Forecast
		{
			get
			{
				if (this.Results.Contains("vy_Forecast"))
				{
					return ((Microsoft.Xrm.Sdk.Money)(this.Results["vy_Forecast"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Money);
				}
			}
			set
			{
				this.Results["vy_Forecast"] = value;
			}
		}
		
		public int VY_OpportunityCount
		{
			get
			{
				if (this.Results.Contains("vy_OpportunityCount"))
				{
					return ((int)(this.Results["vy_OpportunityCount"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["vy_OpportunityCount"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
