#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vy.Crm.Shared.Proxy
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vy_SendQuoteEmail")]
	public partial class VY_SendQuoteEmailRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Target = "Target";
			public const string VY_TemplateId = "VY_TemplateId";
		}
		
		public const string ActionLogicalName = "vy_SendQuoteEmail";
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public string VY_TemplateId
		{
			get
			{
				if (this.Parameters.Contains("vy_TemplateId"))
				{
					return ((string)(this.Parameters["vy_TemplateId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["vy_TemplateId"] = value;
			}
		}
		
		public VY_SendQuoteEmailRequest()
		{
			this.RequestName = "vy_SendQuoteEmail";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
			this.VY_TemplateId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vy_SendQuoteEmail")]
	public partial class VY_SendQuoteEmailResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string VY_EmailId = "VY_EmailId";
		}
		
		public const string ActionLogicalName = "vy_SendQuoteEmail";
		
		public VY_SendQuoteEmailResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference VY_EmailId
		{
			get
			{
				if (this.Results.Contains("vy_EmailId"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["vy_EmailId"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Results["vy_EmailId"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
