#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vy.Crm.Shared.Proxy
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum VY_ActivityType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 3)]
		Email = 127550003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Meeting", 2)]
		Meeting = 127550002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Phone Call", 1)]
		PhoneCall = 127550001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Task", 0)]
		Task = 127550000,
	}
}
#pragma warning restore CS1591
